version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8093:8000"
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nomina
      MYSQL_USER: nomina
      MYSQL_PASSWORD: nomina
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
